/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.descompila.interface_formulario;

/**
 *
 * @author rosae
 */
public class frmUnid2 extends javax.swing.JFrame {

    /**
     * Creates new form frmUnid2
     */
    public frmUnid2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntBloco1 = new javax.swing.JButton();
        bntBloco2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntBackUnidade1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntBloco1.setText("Bloco 1");
        bntBloco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBloco1ActionPerformed(evt);
            }
        });

        bntBloco2.setText("Bloco 2");
        bntBloco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBloco2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Unidade 2");

        bntBackUnidade1.setText("Voltar");
        bntBackUnidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBackUnidade1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntBloco2)
                            .addComponent(bntBloco1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntBackUnidade1)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntBackUnidade1)))
                .addGap(53, 53, 53)
                .addComponent(bntBloco1)
                .addGap(67, 67, 67)
                .addComponent(bntBloco2)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBackUnidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBackUnidade1ActionPerformed
        frmPatrimonio objbackpatrimonio = new frmPatrimonio();
        objbackpatrimonio.setVisible(true);
    }//GEN-LAST:event_bntBackUnidade1ActionPerformed

    private void bntBloco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBloco1ActionPerformed
        frmSalasBloc1 objsalasbloco1 = new frmSalasBloc1();
        objsalasbloco1.setVisible(true);
    }//GEN-LAST:event_bntBloco1ActionPerformed

    private void bntBloco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBloco2ActionPerformed
        frmSalasBloco2 objsalasbloco2 = new frmSalasBloco2();
        objsalasbloco2.setVisible(true);
    }//GEN-LAST:event_bntBloco2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUnid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUnid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUnid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUnid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUnid2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBackUnidade1;
    private javax.swing.JButton bntBloco1;
    private javax.swing.JButton bntBloco2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
